import type { IdentityRefusalCode } from '../domain/identity.errors.ts';

export const IDENTITY_ERROR_STATUSES = {
    IDENTITY_CREDENTIALS_INVALID: 401,
    IDENTITY_SESSION_REQUIRED: 401,
    IDENTITY_ORIGIN_FORBIDDEN: 403,
    IDENTITY_PASSWORD_WEAK: 400,
    IDENTITY_PHONE_INVALID: 400,
    IDENTITY_CODE_INVALID: 401,
    IDENTITY_CODE_EXPIRED: 401,
    IDENTITY_PENDING_TOKEN_INVALID: 401,
    IDENTITY_CONSENT_VERSION_OUTDATED: 409,
} satisfies Record<IdentityRefusalCode, number>;
